version: '3'

services:
  api:
    build:
      context: .
    networks:
      - traefik
    labels:
      - "traefik.http.routers.songs-api.rule=Host(`songs.localhost`)"
      - "traefik.http.services.songs-api.loadbalancer.server.port=9865"

networks:
  traefik:
    external: true