services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    ports:
      - "8080:8081"
    networks:
      - ecoCuenta

  mysql_db:
    container_name: mysql
    image: mysql:8.2.0
    restart: always
    ports:
      - "5432:3306"
    environment:
      MYSQL_USER: backendapp
      MYSQL_PASSWORD: qwerty
      MYSQL_ROOT_PASSWORD: rootbackendapp
      MYSQL_DATABASE: db_backend
    networks:
      - ecoCuenta

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - mysql_db
    ports:
      - "9090:8080"
    networks:
      - ecoCuenta

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - ecoCuenta

networks:
  ecoCuenta:
    driver: bridge