services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_backend?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=backendapp
      - SPRING_DATASOURCE_PASSWORD=qwerty
    depends_on:
      - db
    ports:
      - "8080:8081"
    networks:
      - ecoCuenta

  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: backendapp
      MYSQL_PASSWORD: qwerty
      MYSQL_ROOT_PASSWORD: rootbackendapp
      MYSQL_DATABASE: db_backend
    networks:
      - ecoCuenta

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "9090:8080"
    networks:
      - ecoCuenta

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - URL_BACKEND=http://backend:8080
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - ecoCuenta

networks:
  ecoCuenta:
    driver: bridge